// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH9MbVeSNQp-0zOcS2bj5AqTcI2Lo_ZxA',
    appId: '1:334711603082:web:0754fcd3d456c7ed119273',
    messagingSenderId: '334711603082',
    projectId: 'maildude-c856b',
    authDomain: 'maildude-c856b.firebaseapp.com',
    databaseURL: 'https://maildude-c856b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maildude-c856b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC10yqVFWFeGwfg0NacmryZRkuWzZjIWps',
    appId: '1:334711603082:android:780c483bdffd8ff9119273',
    messagingSenderId: '334711603082',
    projectId: 'maildude-c856b',
    databaseURL: 'https://maildude-c856b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maildude-c856b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNiTGcBUVLPlRSpe8mwF1RZzQFwL03sdE',
    appId: '1:334711603082:ios:71bea708cffb2dae119273',
    messagingSenderId: '334711603082',
    projectId: 'maildude-c856b',
    databaseURL: 'https://maildude-c856b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maildude-c856b.firebasestorage.app',
    iosBundleId: 'com.example.mailDude',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNiTGcBUVLPlRSpe8mwF1RZzQFwL03sdE',
    appId: '1:334711603082:ios:71bea708cffb2dae119273',
    messagingSenderId: '334711603082',
    projectId: 'maildude-c856b',
    databaseURL: 'https://maildude-c856b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maildude-c856b.firebasestorage.app',
    iosBundleId: 'com.example.mailDude',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH9MbVeSNQp-0zOcS2bj5AqTcI2Lo_ZxA',
    appId: '1:334711603082:web:49f5dabb2fed6224119273',
    messagingSenderId: '334711603082',
    projectId: 'maildude-c856b',
    authDomain: 'maildude-c856b.firebaseapp.com',
    databaseURL: 'https://maildude-c856b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maildude-c856b.firebasestorage.app',
  );
}
